// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_-_ABG_KhdOnJVNwHdbrWvv4OuenwoRw',
    appId: '1:112459870697:android:2646dfef4438d1c6355b78',
    messagingSenderId: '112459870697',
    projectId: 'techno-staff',
    storageBucket: 'techno-staff.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLYWRnvTDdhp9ABL6hgDDZcDg5q2maxMs',
    appId: '1:112459870697:web:212547f384b9e6ef355b78',
    messagingSenderId: '112459870697',
    projectId: 'techno-staff',
    authDomain: 'techno-staff.firebaseapp.com',
    storageBucket: 'techno-staff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfMqFAJjO-ezQi5BIUfXUCw6jA1EVf5zw',
    appId: '1:112459870697:ios:8549bc4e34fc4828355b78',
    messagingSenderId: '112459870697',
    projectId: 'techno-staff',
    storageBucket: 'techno-staff.firebasestorage.app',
    iosBundleId: 'com.mohamedodeh.technostaff',
  );

}